env: flex
runtime: java
runtime_config:
  jdk: openjdk14

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2.0
  disk_size_gb: 10

handlers:
  - url: /.*
    script: this field is required, but ignored